/**
 * Sprite editor project model + codegen.
 *
 * Pixels are palette INDICES (roles), capped at 16 colors — that 16-color
 * limit is what reads as "8-bit". A project carries one or more named palette
 * variants (e.g. rarity tiers) that all share those roles, so swapping the
 * palette recolors every frame for free — the whole point of the indexed
 * format. Each color is a 24-bit 0xRRGGBB int (no quantization).
 *
 * Outputs from one source:
 *   - the .json project (source of truth, committed to git)
 *   - a TypeScript module (imported by the game)
 */

export const PALETTE_SIZE = 16; // 16-color cap (4-bit indices)
export const TRANSPARENT_INDEX = 0;

/** A named palette variant. `colors[0]` is the transparent slot; its value is ignored at render time. */
export interface Palette {
  name: string;
  rarity: string;
  colors: number[];
}

export interface SpriteProject {
  name: string;
  width: number;
  height: number;
  depth: 4;
  /** Variants sharing the same index roles. [0] is the base/default. */
  palettes: Palette[];
  /** Each frame is width*height palette indices, row-major. */
  frames: number[][];
}

export function newProject(name: string, width: number, height: number): SpriteProject {
  return {
    name,
    width,
    height,
    depth: 4,
    palettes: [{ name: "base", rarity: "common", colors: [0x000000, 0x000000, 0xffffff] }],
    frames: [blankFrame(width, height)],
  };
}

export function blankFrame(width: number, height: number): number[] {
  return new Array(width * height).fill(TRANSPARENT_INDEX);
}

/** A new variant cloned from an existing one (preserves role count). */
export function clonePalette(src: Palette, name: string): Palette {
  return { name, rarity: src.rarity, colors: src.colors.slice() };
}

// --- project (de)serialize ---

export function toJson(p: SpriteProject): string {
  return JSON.stringify(p, null, 2);
}

interface LegacyProject {
  palette?: number[];
  palettes?: Palette[];
  width?: number;
  height?: number;
  frames?: number[][];
  name?: string;
}

export function fromJson(text: string): SpriteProject {
  const o = JSON.parse(text) as LegacyProject;
  if (!o.width || !o.height || !Array.isArray(o.frames)) {
    throw new Error("not a valid sprite project");
  }
  // Migrate the old single-palette format.
  let palettes = o.palettes;
  if (!palettes && Array.isArray(o.palette)) {
    palettes = [{ name: "base", rarity: "common", colors: o.palette }];
  }
  if (!palettes || !palettes.length) throw new Error("project has no palettes");
  return {
    name: o.name ?? "sprite",
    width: o.width,
    height: o.height,
    depth: 4,
    palettes,
    frames: o.frames,
  };
}

// --- single palette (de)serialize (.pal.json) ---

export function paletteToJson(pal: Palette): string {
  return JSON.stringify({ name: pal.name, rarity: pal.rarity, colors: pal.colors }, null, 2);
}

export function paletteFromJson(text: string): Palette {
  const o = JSON.parse(text) as Partial<Palette>;
  if (!Array.isArray(o.colors) || o.colors.length < 1) throw new Error("not a valid palette");
  const colors = o.colors.slice(0, PALETTE_SIZE).map((c) => c & 0xffffff);
  return { name: o.name ?? "imported", rarity: o.rarity ?? "common", colors };
}

// --- codegen ---

function constName(name: string): string {
  const s = name.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "").toUpperCase();
  return /^[A-Z]/.test(s) ? s : "SPRITE_" + s;
}

function key(name: string, used: Set<string>): string {
  let k = name.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "").toLowerCase();
  if (!k || !/^[a-z]/.test(k)) k = "p_" + k;
  let out = k;
  let n = 1;
  while (used.has(out)) out = k + "_" + n++;
  used.add(out);
  return out;
}

function hex24(c: number): string {
  return "0x" + (c & 0xffffff).toString(16).padStart(6, "0");
}

/** Pad a variant's colors to the full 16 slots so any index resolves to a color. */
function padded(colors: number[]): number[] {
  const out = colors.slice(0, PALETTE_SIZE);
  while (out.length < PALETTE_SIZE) out.push(0);
  return out;
}

/** Chunk a flat index array into width-sized rows for readable output. */
function rows(frame: number[], width: number): string[] {
  const out: string[] = [];
  for (let i = 0; i < frame.length; i += width) out.push(frame.slice(i, i + width).join(", "));
  return out;
}

export function toTypeScript(p: SpriteProject): string {
  const NAME = constName(p.name);
  const used = new Set<string>();
  const palettes = p.palettes
    .map((pal) => `    ${key(pal.name, used)}: Uint32Array.from([${padded(pal.colors).map(hex24).join(", ")}]),`)
    .join("\n");
  const frames = p.frames
    .map((f) => `    Uint8Array.from([\n      ${rows(f, p.width).join(",\n      ")},\n    ])`)
    .join(",\n");
  return `// AUTO-GENERATED by \`npm run gen\` from assets/${p.name}.json. Do not hand-edit.
export const ${NAME} = {
  width: ${p.width},
  height: ${p.height},
  depth: ${p.depth},
  transparentIndex: ${TRANSPARENT_INDEX},
  palettes: {
${palettes}
  },
  frames: [
${frames},
  ],
} as const;
`;
}
