/**
 * Asset codegen. Reads every sprite project in assets/*.json (the committed
 * source of truth, authored in editor.html) and regenerates its derived
 * output:
 *   - src/generated/<name>.ts  — emulator + game module
 *
 * The .ts is a build artifact: never hand-edit it, just rerun `npm run gen`.
 * Codegen logic lives in src/editor/project.ts so the editor preview and this
 * utility stay byte-identical.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { constName, fromJson, toTypeScript } from "../src/editor/project";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const ASSETS = join(root, "assets");
const TS_OUT = join(root, "src", "generated");

function ensureDir(dir: string): void {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

if (!existsSync(ASSETS)) {
  console.error(`No assets/ directory at ${ASSETS} — export a .json from editor.html first.`);
  process.exit(1);
}

const files = readdirSync(ASSETS).filter((f) => f.endsWith(".json"));
if (!files.length) {
  console.warn("assets/ has no .json files — nothing to generate.");
  process.exit(0);
}

ensureDir(TS_OUT);

let ok = 0;
const sprites: { name: string; CONST: string }[] = [];
for (const file of files) {
  try {
    const project = fromJson(readFileSync(join(ASSETS, file), "utf8"));
    writeFileSync(join(TS_OUT, `${project.name}.ts`), toTypeScript(project));
    sprites.push({ name: project.name, CONST: constName(project.name) });
    console.log(`✓ ${file} → src/generated/${project.name}.ts`);
    ok++;
  } catch (err) {
    console.error(`✗ ${file}: ${(err as Error).message}`);
    process.exitCode = 1;
  }
}

// Prune orphan modules whose source asset is gone (e.g. after a rename/delete).
const keep = new Set(sprites.map((s) => `${s.name}.ts`).concat("index.ts"));
for (const f of readdirSync(TS_OUT)) {
  if (f.endsWith(".ts") && !keep.has(f)) {
    rmSync(join(TS_OUT, f));
    console.log(`✗ pruned orphan src/generated/${f}`);
  }
}

// Registry index: every sprite by name, so SPRITES self-heals on rename/add.
sprites.sort((a, b) => a.name.localeCompare(b.name));
const index =
  "// AUTO-GENERATED by `npm run gen`. Do not hand-edit.\n" +
  sprites.map((s) => `import { ${s.CONST} } from "./${s.name}";`).join("\n") +
  "\n\n" +
  `export { ${sprites.map((s) => s.CONST).join(", ")} };\n\n` +
  "/** Sprite name (asset filename) -> generated module. */\n" +
  "export const GEN_SPRITES = {\n" +
  sprites.map((s) => `  ${JSON.stringify(s.name)}: ${s.CONST},`).join("\n") +
  "\n};\n";
writeFileSync(join(TS_OUT, "index.ts"), index);

console.log(`Generated ${ok} sprite${ok === 1 ? "" : "s"} + registry.`);
